// flow-typed signature: 66fb58c2064ae643aac22cb87230674c
// flow-typed version: <<STUB>>/module_vx/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare var module: {
  hot: {
    accept(path: string, callback: () => void): void
  }
}

declare var key: (input: string, action: Function)