#import "./../fragments/note.gql"
#import "./../fragments/project.gql"
query getNoteResults($ids: [String]) {
  Notes(ids: $id) {
    ...NoteFragment
    project {
      ...ProjectFragment
    }
  }
}