#import "./../fragments/project.gql"
#import "./../fragments/category.gql"
#import "./../fragments/note.gql"
query getProject($id: String!) {
  Projects(ids: [$id]) {
    ...ProjectFragment
    category {
      ...CategoryFragment
    }
    notes {
      ...NoteFragment
    }
  }
}
