#import "./../fragments/category.gql"
#import "./../fragments/project.gql"
#import "./../fragments/note.gql"

query getUserData {
  Projects {
    ...ProjectFragment
    category {
    ...CategoryFragment
    }
    notes {
      ...NoteFragment
    }
  }
}